inheritedBy:
    toolchain: node

tasks:
    lint:
        command: pnpm
        args:
            - exec
            - eslint
            - --fix
            - --quiet
            - --cache
            - --concurrency
            - auto

    pnpm:
        command: pnpm
        options:
            cache: false
            interactive: true
            runFromWorkspaceRoot: true

    portless:
        command: pnpm
        args:
            - exec
            - portless
        preset: server
        options:
            cache: false
            interactive: true
            runFromWorkspaceRoot: false
